find the most similar sentence

In [ ]:
import nltk
from nltk.stem import WordNetLemmatizer

In [ ]:
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
nltk.download('wordnet')

In [16]:
text = "Originally , vegetables were  collected from the wild by hunter-gatherers. Vegetables are all plants . Vegetables can be eaten either raw or cooked ."
question = "what are vegetables?"

In [17]:
lemmatizer = WordNetLemmatizer()

In [19]:
def lemma_me(sent):
    sentence_lemmas = []
    sentence_token =  nltk.word_tokenize(sent.lower())
    pos_tags = nltk.pos_tag(sentence_token)
    for token,pos in zip(sentence_token,pos_tags):
        if (pos[1][0].lower() in ['n','v','r','a']):
            lemma = lemmatizer.lemmatize(token,pos[1][0].lower())
            sentence_lemmas.append(lemma)
    return sentence_lemmas 

In [39]:
sentence_tokens = nltk.sent_tokenize(text)
sentence_tokens.append(question)
sentence_tokens

['Originally , vegetables were  collected from the wild by hunter-gatherers.',
 'Vegetables are all plants .',
 'Vegetables can be eaten either raw or cooked .',
 'what are vegetables?']

In [33]:
from sklearn.feature_extraction.text import TfidfVectorizer


In [34]:
tv = TfidfVectorizer(tokenizer=lemma_me)
tv

TfidfVectorizer(tokenizer=<function lemma_me at 0x000001FB4C95FF40>)

In [35]:
tf = tv.fit_transform(sentence_tokens)
tf

c:\Users\ram14\anaconda3\lib\site-packages\sklearn\feature_extraction\text.py:528: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(


<4x8 sparse matrix of type '<class 'numpy.float64'>'
	with 14 stored elements in Compressed Sparse Row format>

In [36]:
array_val = tf.toarray()

In [37]:
array_val

array([[0.27717414, 0.53114624, 0.        , 0.        , 0.53114624,
        0.53114624, 0.        , 0.27717414],
       [0.41988018, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.8046125 , 0.41988018],
       [0.32713399, 0.        , 0.62688384, 0.62688384, 0.        ,
        0.        , 0.        , 0.32713399],
       [0.70710678, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.70710678]])

In [38]:
import pandas as pd
df = pd.DataFrame(tf.toarray(),columns=tv.get_feature_names_out())
df

be   collect      cook       eat  hunter-gatherer  originally  \
0  0.277174  0.531146  0.000000  0.000000         0.531146    0.531146   
1  0.419880  0.000000  0.000000  0.000000         0.000000    0.000000   
2  0.327134  0.000000  0.626884  0.626884         0.000000    0.000000   
3  0.707107  0.000000  0.000000  0.000000         0.000000    0.000000   

      plant  vegetable  
0  0.000000   0.277174  
1  0.804612   0.419880  
2  0.000000   0.327134  
3  0.000000   0.707107

In [52]:
from sklearn.metrics.pairwise import cosine_similarity
values = cosine_similarity(tf[-1],tf)
values

array([[0.39198343, 0.59380024, 0.46263733, 1.        ]])

In [51]:
index = values.argsort()[0][-2]
index

1

In [53]:
values_flat = values.flatten()
values  

array([[0.39198343, 0.59380024, 0.46263733, 1.        ]])

In [54]:
values_flat.sort()
values_flat

array([0.39198343, 0.46263733, 0.59380024, 1.        ])

In [ ]:
coefficient = values_flat[-2]
coefficient

In [58]:
if coefficient>0.3:
    print(sentence_tokens[index])

Vegetables are all plants .
